config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
    get '/about' => 'public/homes#about'
    get '/admin' => 'admin/homes#top'

  # 管理者用
  # URL /admin/sign_in ...
    devise_for :admin,skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
  # 顧客用
   #URL /customers/sign_in...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do

      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :orders
      resources :genres, except: [:destroy, :show]
      resources :order_details
    end

  scope module: :public do

    resources :items, only: [:index, :show]
    get 'customers/unsubscribe'
    get 'customers/check'
    get 'customers/mypage', to: 'customers#show', as: 'mypage'
    get 'customers/information/edit', to: 'customers#edit', as: 'edit_information'
    patch 'customers/information', to: 'customers#update'
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :cart_items, only: [:create, :index, :update, :destroy] do
     collection do
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :shipname, presence: true

  def address_display
  '〒' + post_code + ' ' + address + ' ' + shipname
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer
 validates :quantity, presence: true

  def subtotal
    (item.price * 1.1).round * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :orders, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :family_name, presence: true
  validates :first_name_kana, presence: true
  validates :family_name_kana, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phonenumber, presence: true, length: {maximum: 11, minimum: 10}

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def name
    family_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  # itemとgenreを結びつける設定
  # # dependent: :destroyは、has_manyで使えるオプションです。 1:Nの関係において、
  # 「1」のデータが削除された場合、関連する「N」のデータも削除される設定
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true  #入力値が空でないこと

  # megeという名前でActiveStorageで商品画像を保存できるように設定
  has_one_attached :image
  has_many :cart_items
  has_many :order_details
  # itemとgenreを結びつける設定
  belongs_to :genre  # ジャンルに属する

  #商品画像設定
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    # メソッドに対して引数を設定し、引数に設定した値に画像のサイズを変換するように設定
    image.variant(resize_to_fit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord

 has_many :items, through: :cart_item
 has_many :order_details, dependent: :destroy
 belongs_to :customer

 enum payment_method: { credit_card: 0, transfer: 1 }

 enum orders_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}


  def subtotal
      price * quantiy
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}


 def subtotal
   price * quantity
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to action: :index
    else
      flash.now[:alert] = "登録できませんでした。"
      @genres = Genre.all
      render action: :index
    end
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def show
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find_by(id: params[:id])
  end

  def update
    @genre = Genre.find_by(id: params[:id])
    if @genre.update(genre_params)
      redirect_to action: :index
    else
      flash.now[:alert] = "更新できませんでした。"
      @genres = Genre.all
      render action: :index
    end
  end

private
  def genre_params
#params.permit(:name)
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @item = Item.new
  end

  # 商品一覧
  def index
    @items = Item.page(params[:page]).per(10)    # Itemの取得、1ページに10件表示
  end

  # 商品新規登録：作成データの保存
  def create
     @item = Item.new(item_params)
    # バリデーション設定（カラムが存在しているかのチェック）
    if @item.save
        # 新規投稿が成功したとき:フラッシュメッセージ
        flash[:notice] = "新規登録が完了しました。"
        # 新規登録に成功したら「商品詳細」に遷移する。
        redirect_to admin_item_path(@item)
    else
        flash[:danger] = "登録内容に不備があります。"
        render :new
    end
  end

  # 商品詳細
  def show
     @item = Item.find(params[:id])    # Itemの取得
  end

  # 商品編集
  def edit
    @item = Item.find(params[:id])    # Itemの取
  end

  # 更新処理
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      # 変更が成功したとき:フラッシュメッセージ
       flash[:notice] = "変更が完了しました。"
       redirect_to admin_item_path(@item)   # 商品詳細ページへのパス
    else
       # 変更が成功したとき:フラッシュメッセージ
       flash[:notice] = "変更内容に不備があります。"
       @item.all
       render :edit
    end
  end

  private

  # 作成データのストロングパラメータ（ユーザーから送信されるデータを制限する機能）の設定
  def item_params
    # 設定内容：商品名、商品説明、ジャンルID、税抜価格、販売ステータス
    params.require(:item).permit(:name, :description, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:is_deleted])
  end

private
  def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
          admin_orders_path
      else
          root_path
      end
  end

  def
  after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/edit.html.erb
<!-- 商品編集 -->
<main>
  <div class="container">
    <div class="row" style="margin-top: 5%">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h3 class="card-body bg-light">商品編集</h3>

        <div>
          <%= form_with(model: @item, url: admin_item_path , local: true) do |f| %>   <!-- 商品情報更新の設定-->
            <!-- エラーメッセージ-->
            <%= render 'admin/shared/error_messages', resource: @item %>

            <!-- 画像 -->
            <div class="field">
              <div class="商品画像">
              <%= f.label :"商品画像" %>
              <%= f.file_field :image, placeholder: "Image", accept: "image/*" %>
            </div>

            <div class="field">
              <%= f.label :"商品名" %>
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.label :"商品説明" %>
              <%= f.text_area :description %>
            </div>

            <div class="field">
              <%= f.label :"ジャンル" %>
              <%= f.collection_select :genre_id, Genre.all, :id,  :name, :prompt => "-- 選択してください --" %>
            </div>

            <div class="field">
              <%= f.label :"税抜価格" %>
              <%= f.text_field :price %>
            </div>

            <div class="field">
              <%= f.label :"販売ステータス" %>
              <!-- ラジオボタン -->
              <%= f.radio_button :is_active, :true, checked: true %>
              <%= f.label :is_active_true, "販売中" %>

              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active_false, "販売中止" %>
            </div>

            <div class="actions">
              <%= f.submit "変更を保存", class: "btn btn-success" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/admin/items/index.html.erb
<!-- 商品一覧 -->
<div class="container">
  <div class="row" style="margin-top: 5%">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <table class="table">
        <tr>
          <th><h3 class="card-body bg-light">商品一覧　　　　　　　</h3></th>               <!-- タイトル -->
          <th><%= link_to "新規登録", new_admin_item_path, class: "btn btn-primary" %></th> <!-- 新規登録ボタン -->
        <tr>
      </table>

        <table class="table">
          <thead class="thead-light"> <!-- 表の列の見出しを定義 -->
            <!-- 見出し -->
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody> <!--表の行（水平方向）をグループ化 -->
            <% @items.each do |item| %>
              <tr>
                <th><%= item.id %></th>                   <!-- 商品id -->
                <th><%= link_to item.name, admin_item_path(item.id) %></th>   <!-- 商品名：商品詳細ページへのリンク設定 -->
                <th><%= item.price %></th>                <!-- 税抜価格 -->
                <th><%= item.genre.name %></th>           <!-- ジャンル -->
                <th>
                  <% if item.is_active == true %>        <!-- ステータス true：販売中、false：売切れ -->
                    販売中
                  <% else %>
                    販売停止中
                  <% end %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @items, class:"text-center" %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<!-- 商品新規登録 -->
<main>
  <div class="container">
    <div class="row" style="margin-top: 5%">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h3 class="card-body bg-light">商品新規登録</h3>

        <div>
          <%= form_with(model: @item, url: admin_items_path, local: true) do |f| %>   <!-- 新規登録の設定-->
            <!-- エラーメッセージ-->
            <%= render 'admin/shared/error_messages', resource: @item %>

            <!-- 画像 -->
            <div class="field">
              <div class="商品画像">
              <%= f.label :"商品画像" %>
              <%= f.file_field :image, placeholder: "Image", accept: "image/*" %>
            </div>

            <div class="field">
              <%= f.label :"商品名" %>
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.label :"商品説明" %>
              <%= f.text_area :description %>
            </div>

            <div class="field">
              <%= f.label :"ジャンル" %>
              <%= f.collection_select :genre_id, Genre.all, :id,  :name, :prompt => "-- 選択してください --" %>
            </div>

            <div class="field">
              <%= f.label :"税抜価格" %>
              <%= f.text_field :price %>
            </div>

            <div class="field">
              <%= f.label :"販売ステータス" %>
              <!-- ラジオボタン -->
              <%= f.radio_button :is_active, :true, checked: true %>
              <%= f.label :is_active_true, "販売中" %>

              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active_false, "販売中止" %>
            </div>

            <div class="actions">
              <%= f.submit "新規登録", class: "btn btn-success" %>
          <% end %>
          </div>
        </div>
    </div>
  </div>
</main>

app/views/admin/items/show.html.erb
<!-- 商品詳細 -->
<div class="container px-5 px-sm-0">
  <div class="row" style="margin-top: 5%">
    <h2>商品詳細</h2>

    <div class="col-xs-5">
     <!-- 画像 -->
     <%= image_tag @item.get_image(300, 300) %>
    </div>

    <table class="table">
      <tr>
        <th>商品名</th>
        <th><%= @item.name %></th>
      </tr>

      <tr>
        <th>商品説明</th>
        <th><%= @item.description %></th>
      </tr>

      <tr>
        <th>ジャンル</th>
        <th><%= @item.genre.name %></th>
      </tr>

      <tr>
        <th>税込価格<br>(税抜価格)</th>
        <th>
          <%= (@item.price * 1.1).to_i %>(<%= @item.price %>) 円
        </th>
      </tr>

      <tr>
        <th>販売ステータス</th>
        <th>
        <% if @item.is_active == true %>    <!-- ステータス true：販売中、false：売切れ -->
          <p>販売中</p>
        <% else %>
          <p>売切れ</p>
        <% end %>
        </th>
      </tr>
    </table>
    <div>
    <%= link_to '編集する', edit_admin_item_path, class: "btn btn-success"%>
    </div>
  </div>
</div>