config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
    get '/about' => 'public/homes#about'
    get '/admin' => 'admin/homes#top'

  # 管理者用
  # URL /admin/sign_in ...
    devise_for :admin,skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
  # 顧客用
   #URL /customers/sign_in...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do

      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :orders
      resources :genres, except: [:destroy, :show]
      resources :order_details
    end

  scope module: :public do

    resources :items, only: [:index, :show]
    get 'customers/unsubscribe'
    get 'customers/check'
    get 'customers/mypage', to: 'customers#show', as: 'mypage'
    get 'customers/information/edit', to: 'customers#edit', as: 'edit_information'
    patch 'customers/information', to: 'customers#update'
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :cart_items, only: [:create, :index, :update, :destroy] do
     collection do
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord

 has_many :items, through: :cart_item
 has_many :order_details, dependent: :destroy
 belongs_to :customer

 enum payment_method: { credit_card: 0, transfer: 1 }

 enum orders_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}


  def subtotal
      price * quantiy
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @order = Order.page(params[:page])
    customer_id = Customer.find_by(id: @order.ids)
    #@full_name = customer_id.family_name + "" + customer_id.first_name
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<p id="notice"></p>
<div class="container">

  <div class="row">
    <h5 class="bg-light text-dark">注文履歴一覧</h5>
  </div>

  <div class="row">
    <div class="col-md-9 mx-auto">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
        </tr>
      </thead>

      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order.id) do %>
              <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            <% end %>
          </td>
          <td>
            <%= order.customer.family_name  + order.customer.first_name %>
          </td>
          <td>
            <% total_quantity = 0 %>
            <% order.order_details.each do |order_details| %>
              <% total_quantity += order_details.quantity %>
            <% end %>
            <%= total_quantity %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
    </div>
    <!--<div class="col-md-2"></div>-->

  </div>

  <div class="row">
    <div class="d-block mx-auto">
      <%= paginate @orders %>
    </div>
  </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-11 offset-md-1">
      <h1>注文履歴詳細</h1>
      <nav class="nav">
        <a>購入者</a>
        <a>
          <%= link_to admin_customer_path(@order.customer_id) do %>
            <%= @full_name %>
          <% end %>
        </a>
      </nav>
      <nav class="nav">
        <a>注文日</a>
        <a><%= @order.created_at.strftime('%Y/%m/%d') %></a>
      </nav>
      <nav class="nav">
        <a>配送先</a>
        <a><%= @order.post_code %></a>
        <a><%= @order.address %></a></br>
        <a><%= @order.name %></a>
      </nav>
      <nav class="nav">
        <p>支払方法</p>
        <%= @order.payment_method_i18n %>
      </nav>
      <<th>注文ステータス</th>
          <td><%= form_with model: @order, url: admin_order_path do |f| %>
                <%= f.select :orders_status, Order.orders_statuses.keys,class:"orders_status"%>
                <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                <% end %>
          </td>
    </div>
    <div class="col-md-5 offset-md-1">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tbody>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.quantity %></td>
              <td><%= order_detail.price * order_detail.quantity %></td>
            <th>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f|%>
                <%= f.select :production_status, OrderDetail.production_statuses.keys, class:"production_status"%>
                <%= f.submit "更新", class:"btn btn-success"%>
              <% end %>
            </th>
        </tbody>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-11 offset-md-1">
      <nav class="nav">
        <a>商品合計</a>
        <a><%= @order.total_price - @order.postage %>円</a>
      </nav>
      <nav class="nav">
        <a>送料</a>
        <a><%= @order.postage %>円</a>
      </nav>
      <nav class="nav">
        <a>請求金額合計</a>
        <a><%= @order.total_price.to_s(:delimited) %>円</a>
      </nav>
    </div>
  </div>
</div>