config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
    get '/about' => 'public/homes#about'
    get '/admin' => 'admin/homes#top'

  # 管理者用
  # URL /admin/sign_in ...
    devise_for :admin,skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
  # 顧客用
   #URL /customers/sign_in...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do

      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :orders
      resources :genres, except: [:destroy, :show]
      resources :order_details
    end

  scope module: :public do

    resources :items, only: [:index, :show]
    get 'customers/unsubscribe'
    get 'customers/check'
    get 'customers/mypage', to: 'customers#show', as: 'mypage'
    get 'customers/information/edit', to: 'customers#edit', as: 'edit_information'
    patch 'customers/information', to: 'customers#update'
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :cart_items, only: [:create, :index, :update, :destroy] do
     collection do
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  # itemとgenreを結びつける設定
  # # dependent: :destroyは、has_manyで使えるオプションです。 1:Nの関係において、
  # 「1」のデータが削除された場合、関連する「N」のデータも削除される設定
  has_many :item, dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to action: :index
    else
      flash.now[:alert] = "登録できませんでした。"
      @genres = Genre.all
      render action: :index
    end
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def show
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find_by(id: params[:id])
  end

  def update
    @genre = Genre.find_by(id: params[:id])
    if @genre.update(genre_params)
      redirect_to action: :index
    else
      flash.now[:alert] = "更新できませんでした。"
      @genres = Genre.all
      render action: :index
    end
  end

private
  def genre_params
#params.permit(:name)
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row justify-content-start">
    <div class="col-auto offset-1">
    <span style="background-color:#DCDCDC">　ジャンル編集　</span>
  </div>

<!-- 編集フォーム -->
<%= form_with model: @genre,url: admin_genre_path, local: true do |f| %>  <div class="row g-3 align-items-center">
    <div class="col-auto">
      <label class="col-form-label">ジャンル名</label></div>
        <div class="col-auto">
        <%= f.text_field :name, placeholder: "ジャンル名" %></div>
      <div class="col-auto">
      <%= f.submit "変更を保存", class: 'btn btn-success' %></div>
    </div>
  </div>
<% end %>

app/views/admin/genres/index.html.erb
<div data-turbolinks="false">
  <div class="container">
    <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: "alert alert-danger" %>
    <% end %>
    <div class="row justify-content-start">
      <div class="col-auto offset-1 g-3 my-4">
      <span style="background-color:#DCDCDC">　ジャンル一覧・追加　</span>
    </div>

  <!-- 新規投稿画面 -->
  <%= form_with(model: @genre , url: admin_genres_path, local: true )do |f| %>
    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <label class="col-form-label">ジャンル名</label></div>
          <div class="col-auto">
          <%= f.text_field :name, placeholder: "ジャンル名" %></div>
        <div class="col-auto">
        <%= f.submit "　新規登録　", class: 'btn btn-success btn-sm' %></div>
      </div>
    </div>
  <% end %>


  <!-- 投稿されたジャンルを表示させる -->
  <div class="row ">
    <div class="col-sm-5 g-3 my-4">
      <table class="table table-sm">
        <thead>
          <tr valign="middle">
            <th class="table-secondary"colspan="2">　　ジャンル　</th>
          </tr>
        </thead>
        <tbody>
        <% @genres.each do |g| %>
        <tr valign="middle">
          <td>　<%= g.name %></td>
          <td align="center"><%= link_to "　編集する　", edit_admin_genre_path(g.id), class: 'btn btn-success btn-sm' %></td>
        </tr>
         <% end %>
         </tbody>
      </table>
    </div>
  </div>
</div>