config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
    get '/about' => 'public/homes#about'
    get '/admin' => 'admin/homes#top'

  # 管理者用
  # URL /admin/sign_in ...
    devise_for :admin,skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
    }
  # 顧客用
   #URL /customers/sign_in...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  namespace :admin do

      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :orders
      resources :genres, except: [:destroy, :show]
      resources :order_details
    end

  scope module: :public do

    resources :items, only: [:index, :show]
    get 'customers/unsubscribe'
    get 'customers/check'
    get 'customers/mypage', to: 'customers#show', as: 'mypage'
    get 'customers/information/edit', to: 'customers#edit', as: 'edit_information'
    patch 'customers/information', to: 'customers#update'
    patch 'customers/withdraw', to: 'customers#withdraw'
    resources :cart_items, only: [:create, :index, :update, :destroy] do
     collection do
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :shipname, presence: true

  def address_display
  '〒' + post_code + ' ' + address + ' ' + shipname
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer
 validates :quantity, presence: true

  def subtotal
    (item.price * 1.1).round * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :orders, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :family_name, presence: true
  validates :first_name_kana, presence: true
  validates :family_name_kana, presence: true
  validates :post_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phonenumber, presence: true, length: {maximum: 11, minimum: 10}

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def name
    family_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  # itemとgenreを結びつける設定
  # # dependent: :destroyは、has_manyで使えるオプションです。 1:Nの関係において、
  # 「1」のデータが削除された場合、関連する「N」のデータも削除される設定
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true  #入力値が空でないこと

  # megeという名前でActiveStorageで商品画像を保存できるように設定
  has_one_attached :image
  has_many :cart_items
  has_many :order_details
  # itemとgenreを結びつける設定
  belongs_to :genre  # ジャンルに属する

  #商品画像設定
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    # メソッドに対して引数を設定し、引数に設定した値に画像のサイズを変換するように設定
    image.variant(resize_to_fit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord

 has_many :items, through: :cart_item
 has_many :order_details, dependent: :destroy
 belongs_to :customer

 enum payment_method: { credit_card: 0, transfer: 1 }

 enum orders_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}


  def subtotal
      price * quantiy
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}


 def subtotal
   price * quantity
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @item = Item.new
  end

  # 商品一覧
  def index
    @items = Item.page(params[:page]).per(10)    # Itemの取得、1ページに10件表示
  end

  # 商品新規登録：作成データの保存
  def create
     @item = Item.new(item_params)
    # バリデーション設定（カラムが存在しているかのチェック）
    if @item.save
        # 新規投稿が成功したとき:フラッシュメッセージ
        flash[:notice] = "新規登録が完了しました。"
        # 新規登録に成功したら「商品詳細」に遷移する。
        redirect_to admin_item_path(@item)
    else
        flash[:danger] = "登録内容に不備があります。"
        render :new
    end
  end

  # 商品詳細
  def show
     @item = Item.find(params[:id])    # Itemの取得
  end

  # 商品編集
  def edit
    @item = Item.find(params[:id])    # Itemの取
  end

  # 更新処理
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      # 変更が成功したとき:フラッシュメッセージ
       flash[:notice] = "変更が完了しました。"
       redirect_to admin_item_path(@item)   # 商品詳細ページへのパス
    else
       # 変更が成功したとき:フラッシュメッセージ
       flash[:notice] = "変更内容に不備があります。"
       @item.all
       render :edit
    end
  end

  private

  # 作成データのストロングパラメータ（ユーザーから送信されるデータを制限する機能）の設定
  def item_params
    # 設定内容：商品名、商品説明、ジャンルID、税抜価格、販売ステータス
    params.require(:item).permit(:name, :description, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:is_deleted])
  end

private
  def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
          admin_orders_path
      else
          root_path
      end
  end

  def
  after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_headder_admin.html.erb
<div class="container">
  <ul class="row">

    <div class="nav-item col-sm-auto">
      <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "注文履歴一覧", admin_orders_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary w-auto' %>
    </div>
  </ul>
  <ul class="row justify-content-end">
    <form class="d-flex" role="search">
      <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </ul>
</div>

app/views/layouts/_headder_customer.html.erb
<div class="container">
  <ul class="row">
    <div class="nav-item col-sm-auto">
      <%= link_to "マイページ", mypage_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary w-auto' %>
    </div>
  </ul>
  <ul class="row justify-content-end">
    <form class="d-flex" role="search">
      <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </ul>
</div>

app/views/layouts/_headder_guest.html.erb
<div class="container-fluid">
  <ul class="row">
    <div class="nav-item col-sm-auto">
      <%= link_to "About", about_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
    <div class="nav-item col-sm-auto">
      <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary w-auto' %>
    </div>
  </ul>
  <ul class="row justify-content-end">
    <form class="d-flex" role="search">
      <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<div data-turbolinks="false">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- logo部分 -->
      <a class="navbar-brand" href="/">LOGO</a>

      <!--ログイン中のアカウント名の表示-->
      <div class="row justify-content-end">
        <div class="col-sm-12">
        <% if customer_signed_in? %>
        <%= "ようこそ、#{ current_customer.family_name } さん！" %>
        <% end %>
        </div>
      </div>
      <!-- ハンバーガーメニュー部分 -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <!--動作と見た目の部分-->
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav navbar-expand">
        <!-- ここに、権限ごとに部分テンプレ化したリンクを実装する-->
        <% if admin_signed_in? %>
          <%= render 'layouts/headder_admin' %>
        <% elsif customer_signed_in? %>
          <%= render 'layouts/headder_customer' %>
        <% else %>
          <%= render 'layouts/headder_guest' %>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <div class="p-3 mb-2 bg-warning text-dark"></div>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class"d-flex flex-column vh-100">

    <header class="shadow-sm">
      <%= render 'layouts/navbar' %>
    </header>

     <%= yield %>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
<!--<p class="bg-primary">primary</p>
    <script src="js/scripts.js"></script>
-->
  </body>
</html>